self host

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -19,8 +19,8 @@ jobs:
             node-version: '16'
 
       - name: Run unit tests
-        run: npm run test
-        npm run test > test-report .txt || echo "Test failed" > test-report.txt
+        run: |
+          npm run test > test-report .txt || echo "Test failed" > test-report.txt
 
       - name: Upload test report
         uses: actions/upload-artifact@v4
